Algoritmo "Ex22 Pot sem Pot"
// 22. Desenvolva um algoritmo que receba dois valores inteiros, x e y, calcule
// e mostre a potência xy, sem utilizar o operador pot.
Var
// Seção de Declarações das variáveis 
   x, y: Inteiro
   a: Real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Valor de X: ")
   Leia(x)
   Escreva("Valor de Y: ")
   Leia(y)
   a <- x^y
   Escreva(a, " é o resultado.")
Fimalgoritmo